format = """\
$directory$git_branch$git_commit$git_state$git_status
$jobs$character"""

[directory]
style = "blue"
truncation_length = 8 
truncation_symbol = "â‹¯"
truncate_to_repo = false
read_only = " ğŸ”’"

[jobs]
style = "yellow"
symbol_threshold = 0
number_threshold = 0

[character]
success_symbol = "[â¯](purple)"
error_symbol = "[â¯](red)"
vimcmd_symbol = "[â®](green)"

[git_branch]
symbol = 'î‚ '
format = '([$symbol $branch(:$remote_branch) ](yellow))'

[git_commit]
format='[\(Detached HEAD: $hash$tag\)](yellow)'

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[git_status]
format = '([$ahead_behind | $all_status](yellow))'
conflicted = "ğŸ’¥[${count}](red)"
ahead = "â‡¡Â·${count}"
behind = "â‡£Â·${count}"
diverged = "â‡•â‡¡Â·${ahead_count}â‡£Â·${behind_count}"
up_to_date = "[âœ“](green)"
untracked = "â€¦${count}"
stashed = "[@${count}](red)"
modified = "[+${count}](purple)"
staged = "[#${count}](purple)"
renamed= "[Â»${count}](purple)"
deleted = "[âœ˜${count}](purple)"

